CREATE TABLE IF NOT EXISTS `book` (
  `user_id` INT UNSIGNED NOT NULL,
  `book_date` DATE NOT NULL ,
  `book_period` TINYINT NOT NULL,
  `priority` TINYINT NOT NULL DEFAULT 0,
  `status` ENUM('WAIT', 'DOING', 'DONE', 'PAUSE') NOT NULL DEFAULT 'WAIT',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `book_date`, `book_period`),
  FOREIGN KEY (`user_id`) REFERENCES `user_info`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB  CHARSET=utf8;